variable "availability_domain" {}
variable "compartment_ocid" {}
variable "subnet_id" {}
variable "instance_name" {}
variable "instance_shape" {}
variable "image_id" {}
variable "public_edge_node" {}
variable "ssh_public_key" {}
variable "oke_cluster_id" {}
variable "nodepool_id" {}
variable "tenancy_ocid" {}
variable "namespace" {}
variable "kube_label" {}
variable "user_data" {}
variable "bastion_flex_gbs" {}
variable "bastion_flex_ocpus" {}
variable "is_flex_shape" {}
variable "kubeflow_login_ocid" {}
variable "kubeflow_password_ocid" {}
variable "kubeflow_login" {}
variable "kubeflow_password" {}
